apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: NodePort   # Set the service type to NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Specify the nodePort value
  selector:
    app: guestbook-ui

